// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjEoTV6IVGLl3RzrOmDoSxCiSxKYpDPpQ',
    appId: '1:673600511306:web:355372526a56646441b5b3',
    messagingSenderId: '673600511306',
    projectId: 'flatflow-app',
    authDomain: 'flatflow-app.firebaseapp.com',
    storageBucket: 'flatflow-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4sN9zPKMXXpcbGrUsl50CF5AMYmyn-Y',
    appId: '1:673600511306:android:4015ae92ab2b6c9941b5b3',
    messagingSenderId: '673600511306',
    projectId: 'flatflow-app',
    storageBucket: 'flatflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd6nyLEuy_rCr4aX1JFqeMcfysrAb17Og',
    appId: '1:673600511306:ios:f9c4ebc3c639f8f241b5b3',
    messagingSenderId: '673600511306',
    projectId: 'flatflow-app',
    storageBucket: 'flatflow-app.firebasestorage.app',
    iosBundleId: 'com.ankitbhardwaj.flatflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd6nyLEuy_rCr4aX1JFqeMcfysrAb17Og',
    appId: '1:673600511306:ios:f9c4ebc3c639f8f241b5b3',
    messagingSenderId: '673600511306',
    projectId: 'flatflow-app',
    storageBucket: 'flatflow-app.firebasestorage.app',
    iosBundleId: 'com.ankitbhardwaj.flatflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjEoTV6IVGLl3RzrOmDoSxCiSxKYpDPpQ',
    appId: '1:673600511306:web:20d4957783c4dcf241b5b3',
    messagingSenderId: '673600511306',
    projectId: 'flatflow-app',
    authDomain: 'flatflow-app.firebaseapp.com',
    storageBucket: 'flatflow-app.firebasestorage.app',
  );
}
